version: 3
images:
  base_image:
    name: registry.fedoraproject.org/fedora:42
additional_build_steps:
  prepend_base:
    - RUN dnf install -y python3-pip
dependencies:
  ansible_core:
    package_pip: ansible-core==2.19.0
  ansible_runner:
    package_pip: ansible-runner==2.4.1
  galaxy: requirements.yml
  python: requirements.txt
